# Generated by Django 2.2.12 on 2020-07-01 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
